Repository CynthiaStephan/Noteo, pull requests merged in 2025-03, with the labels that each got.

#17 page formateur
  client/src/Pages/Formateur/Formateur.css
  client/src/Pages/Formateur/Formateur.jsx
Labels: enhancement

#20 Vérification des routes d'authentifications
  docker-compose.yml
  server/src/controllers/authController.js
  server/src/index.js
Labels: enhancement

#21 Netoyage console log dans les les fichiers auth
  server/src/controllers/authController.js
Labels: chore

#23 filtre par formation
  client/src/Pages/AjoutQuestion/AjoutQuestion.jsx
Labels: enhancement

#25 responsive
  client/src/App.css
  client/src/Pages/AjoutQuestion/AjoutQuestion.css
  client/src/Pages/AjoutQuestion/AjoutQuestion.jsx
  client/src/Pages/Formateur/Formateur.css
  client/src/Pages/Questionnaire/Questionnaire.css
  client/src/Pages/Questionnaire/Questionnaire.jsx
Labels: enhancement

#29 ajout redirection connexion + responsive navbar
  client/src/Nav/Nav.css
  client/src/Nav/NavBase.jsx
  client/src/Nav/NavConnexion.jsx
  client/src/Nav/NavCree.jsx
  client/src/Nav/NavProfil.jsx
  client/src/Pages/AjoutQuestion/AjoutQuestion.css
  client/src/Pages/AjoutQuestion/AjoutQuestion.jsx
  client/src/Pages/Connexion/Connexion.jsx
  client/src/Pages/CreeCompte/CreeCompte.jsx
  client/src/Pages/Questionnaire/Questionnaire.css
  client/src/Pages/Questionnaire/Questionnaire.jsx
Labels: enhancement

#32 creation de question + logout + alert de succes/erreur
  client/src/Nav/NavBase.jsx
  client/src/Pages/AjoutQuestion/AjoutQuestion.css
  client/src/Pages/AjoutQuestion/AjoutQuestion.jsx
  client/src/Pages/Connexion/Connexion.jsx
Labels: enhancement

#34 modification divers
  client/src/Pages/AjoutQuestion/AjoutQuestion.jsx
  client/src/Pages/Connexion/Connexion.jsx
  client/src/Pages/CreeCompte/CreeCompte.jsx
  client/src/Pages/Formateur/Formateur.css
  client/src/Pages/Formateur/Formateur.jsx
  client/src/Pages/Questionnaire/Questionnaire.css
  client/src/Pages/Questionnaire/Questionnaire.jsx
Labels: enhancement

#47 corretion bug
  client/src/Pages/AjoutQuestion/AjoutQuestion.jsx
  client/src/Pages/Formateur/Formateur.jsx
  client/src/Pages/Questionnaire/Questionnaire.jsx
Labels: bug
